import type { Metadata } from "next";
import "./globals.css";
import Providers from "../Providers/Providers";

export const metadata: Metadata = {
  title: "HealHub",
  description: "Generated by create next app",
  icons: {
    icon: "/health-_1_.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="favicon" href="/health.ico" />
      </head>
      <body className="antialiased">


<Providers>   
  
         {children}
</Providers>
     
           
       

      
      </body>
    </html>
  );
}

